--- #YAML:1.0
name:               types
version:            0.05_02
abstract:           type declaration and checking
author:
    - Artur Bergman <abergman@cpan.org>, Reini Urban <rurban@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Generate:  1.34
    B::Utils:     0
    Hook::Scope:  0.04
    optimize:     0.02
    optimizer:    0.05
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    B::C:  1.30
